use connectrpc::{Context, ConnectError, ErrorCode};
use anyhow::Context as _;
use buffa::view::OwnedView;
use tracing::{info, error, warn};
use gridtokenx_blockchain_core::auth::ServiceRole;

// Generated code from proto
#[allow(clippy::module_inception)]
pub mod chain_v1 {
    include!(concat!(env!("OUT_DIR"), "/_chain_bridge_include.rs"));
    pub use gridtokenx::chain::v1::*;
}

// Ensure these imports match what is generated by `buffa` mapped from `chain_bridge.proto`.
use chain_v1::{
    ChainBridgeService,
    GetBalanceRequest, GetBalanceRequestView, GetBalanceResponse,
    GetAccountDataRequest, GetAccountDataRequestView, GetAccountDataResponse,
    GetLatestBlockhashRequest, GetLatestBlockhashRequestView, GetLatestBlockhashResponse,
    GetRecentPrioritizationFeesRequest, GetRecentPrioritizationFeesRequestView, GetRecentPrioritizationFeesResponse,
    GetTokenAccountBalanceRequest, GetTokenAccountBalanceRequestView, GetTokenAccountBalanceResponse,
    GetSignatureStatusRequest, GetSignatureStatusRequestView, GetSignatureStatusResponse,
    GetSlotRequest, GetSlotRequestView, GetSlotResponse,
    SimulateTransactionRequest, SimulateTransactionRequestView, SimulateTransactionResponse,
    SubmitTransactionRequest, SubmitTransactionRequestView, SubmitTransactionResponse,
    PrioritizationFee,
    GetEpochInfoRequest, GetEpochInfoRequestView, GetEpochInfoResponse,
    RequestAirdropRequest, RequestAirdropResponse,
    GetTransactionDetailsRequest, GetTransactionDetailsResponse,
};

use solana_client::nonblocking::rpc_client::RpcClient;
use solana_client::client_error::ClientError;
use solana_sdk::account::Account;
use solana_sdk::hash::Hash;
use solana_sdk::signature::Signature;
use solana_client::rpc_response::{Response, RpcSimulateTransactionResult, RpcPrioritizationFee};
use std::str::FromStr;
use solana_sdk::pubkey::Pubkey;
use solana_sdk::transaction::Transaction;
use std::sync::Arc;
use async_trait::async_trait;
use tokio::sync::RwLock;

/// Blockhash cache for high-throughput signing
pub struct BlockhashCache {
    current: RwLock<Option<(Hash, u64)>>,
}

impl BlockhashCache {
    pub fn new() -> Self {
        Self {
            current: RwLock::new(None),
        }
    }

    pub async fn update(&self, hash: Hash, last_valid_block_height: u64) {
        let mut lock = self.current.write().await;
        *lock = Some((hash, last_valid_block_height));
    }

    pub async fn get(&self) -> Option<(Hash, u64)> {
        *self.current.read().await
    }
}

/// Abstraction layer for Solana RPC interactions to enable mocking in tests.
#[async_trait]
pub trait SolanaProvider: Send + Sync {
    async fn simulate_transaction(&self, transaction: &Transaction) -> Result<Response<RpcSimulateTransactionResult>, ClientError>;
    async fn send_transaction(&self, transaction: &Transaction) -> Result<Signature, ClientError>;
    async fn get_latest_blockhash(&self) -> Result<(Hash, u64), ClientError>;
    async fn get_balance(&self, pubkey: &Pubkey) -> Result<u64, ClientError>;
    async fn get_account(&self, pubkey: &Pubkey) -> Result<Account, ClientError>;
    async fn get_recent_prioritization_fees(&self, pubkeys: &[Pubkey]) -> Result<Vec<RpcPrioritizationFee>, ClientError>;
    async fn get_token_account_balance(&self, pubkey: &Pubkey) -> Result<serde_json::Value, ClientError>;
    async fn get_signature_statuses(&self, signatures: &[Signature]) -> Result<Response<Vec<Option<serde_json::Value>>>, ClientError>;
    async fn get_slot(&self) -> Result<u64, ClientError>;
    async fn request_airdrop(&self, pubkey: &Pubkey, lamports: u64) -> Result<Signature, ClientError>;
    async fn get_transaction(&self, signature: &Signature) -> Result<serde_json::Value, ClientError>;
    async fn get_epoch_info(&self) -> Result<solana_sdk::epoch_info::EpochInfo, ClientError>;
}

/// Real implementation of SolanaProvider using RpcClient.
pub struct RealSolanaProvider {
    client: RpcClient,
}

impl RealSolanaProvider {
    pub fn new(rpc_url: String) -> Self {
        Self {
            client: RpcClient::new(rpc_url),
        }
    }
}

#[async_trait]
impl SolanaProvider for RealSolanaProvider {
    async fn simulate_transaction(&self, transaction: &Transaction) -> Result<Response<RpcSimulateTransactionResult>, ClientError> {
        info!("Simulating transaction...");
        for (i, msg) in transaction.message.instructions.iter().enumerate() {
            info!("Instruction {}: program_id_index={}", i, msg.program_id_index);
            for (j, acc_idx) in msg.accounts.iter().enumerate() {
                if let Some(pubkey) = transaction.message.account_keys.get(*acc_idx as usize) {
                    info!("  Account {}: {}", j, pubkey);
                }
            }
        }
        self.client.simulate_transaction(transaction).await
    }
    async fn send_transaction(&self, transaction: &Transaction) -> Result<Signature, ClientError> {
        self.client.send_transaction(transaction).await
    }
    async fn get_latest_blockhash(&self) -> Result<(Hash, u64), ClientError> {
        self.client.get_latest_blockhash_with_commitment(self.client.commitment()).await
    }
    async fn get_balance(&self, pubkey: &Pubkey) -> Result<u64, ClientError> {
        self.client.get_balance(pubkey).await
    }
    async fn get_account(&self, pubkey: &Pubkey) -> Result<Account, ClientError> {
        self.client.get_account(pubkey).await
    }
    async fn get_recent_prioritization_fees(&self, pubkeys: &[Pubkey]) -> Result<Vec<RpcPrioritizationFee>, ClientError> {
        self.client.get_recent_prioritization_fees(pubkeys).await
    }
    async fn get_token_account_balance(&self, pubkey: &Pubkey) -> Result<serde_json::Value, ClientError> {
        self.client.get_token_account_balance(pubkey).await.map(|b| serde_json::to_value(b).unwrap())
    }
    async fn get_signature_statuses(&self, signatures: &[Signature]) -> Result<Response<Vec<Option<serde_json::Value>>>, ClientError> {
        let resp = self.client.get_signature_statuses(signatures).await?;
        let value = resp.value.into_iter().map(|opt| opt.map(|s| serde_json::to_value(s).unwrap())).collect();
        Ok(Response { context: resp.context, value })
    }
    async fn get_slot(&self) -> Result<u64, ClientError> {
        self.client.get_slot().await
    }
    async fn request_airdrop(&self, pubkey: &Pubkey, lamports: u64) -> Result<Signature, ClientError> {
        self.client.request_airdrop(pubkey, lamports).await
    }
    async fn get_transaction(&self, signature: &Signature) -> Result<serde_json::Value, ClientError> {
        self.client.get_transaction_with_config(
            signature,
            solana_client::rpc_config::RpcTransactionConfig {
                encoding: Some(solana_transaction_status::UiTransactionEncoding::Json),
                commitment: Some(self.client.commitment()),
                max_supported_transaction_version: Some(0),
            }
        ).await.map(|tx| serde_json::to_value(tx).unwrap())
    }
    async fn get_epoch_info(&self) -> Result<solana_sdk::epoch_info::EpochInfo, ClientError> {
        let info = self.client.get_epoch_info().await?;
        Ok(solana_sdk::epoch_info::EpochInfo {
            absolute_slot: info.absolute_slot,
            block_height: info.block_height,
            epoch: info.epoch,
            slots_in_epoch: info.slots_in_epoch,
            slot_index: info.slot_index,
            transaction_count: info.transaction_count,
        })
    }
}

use litesvm::LiteSVM;

/// Implementation of SolanaProvider using LiteSVM for in-memory simulation.
/// It can lazily fetch accounts from a real RPC to simulate mainnet state.
pub struct SurfpoolSolanaProvider {
    svm: Arc<RwLock<LiteSVM>>,
    rpc_client: Option<RpcClient>,
}

impl SurfpoolSolanaProvider {
    pub async fn new(rpc_url: Option<String>) -> anyhow::Result<Self> {
        let svm = LiteSVM::new();
        let rpc_client = rpc_url.map(RpcClient::new);
        
        info!("🌊 Surfpool (LiteSVM) initialized");
        if rpc_client.is_some() {
            info!("🔗 Mainnet state cloning enabled via RPC");
        }
        
        let mut provider = Self {
            svm: Arc::new(RwLock::new(svm)),
            rpc_client,
        };
        
        provider.deploy_core_programs().await?;
        
        Ok(provider)
    }

    async fn deploy_core_programs(&mut self) -> anyhow::Result<()> {
        let mut svm = self.svm.write().await;
        
        let programs = [
            ("HZR6b8GhzhDowyL6dX58qBjdSDNtFyJHU5dPF3kXDcTS", "gridtokenx-anchor/target/deploy/registry.so"),
            ("GjSjmPt8VSHr49ti4BijWZSu7rwb8o32pod7gNBnTY4U", "gridtokenx-anchor/target/deploy/energy_token.so"),
            ("DXxHdUar3pUUKRnt4XAMA8rdYRpAsNY1xk3Zo4crShvY", "gridtokenx-anchor/target/deploy/trading.so"),
            ("AiWcoPDEk3G4iKrDXj1wCN1ffWxQDEsgtJZKcjauoFJr", "gridtokenx-anchor/target/deploy/oracle.so"),
            ("6FsfuFEg8LHjSiejc8om8Q6iSaAgfEWHCgz78PT8jocw", "gridtokenx-anchor/target/deploy/governance.so"),
        ];

        for (id_str, path) in programs {
            let pubkey = Pubkey::from_str(id_str)?;
            let address = solana_address::Address::from(pubkey.to_bytes());
            
            if let Ok(program_data) = std::fs::read(path) {
                info!("🚀 Deploying program {} from {} to LiteSVM", id_str, path);
                let _ = svm.add_program(address, &program_data);
            } else {
                warn!("⚠️ Could not find program SO at {}. Skipping deployment for {}.", path, id_str);
            }
        }

        // --- PDA CALCULATIONS ---
        let auth_pubkey = Pubkey::from_str("EzudwoHvNPAc4dpPi5ndU8MEZVHVzq3Pj3Thm9ooKmiJ")?;
        let registry_program_id = Pubkey::from_str("HZR6b8GhzhDowyL6dX58qBjdSDNtFyJHU5dPF3kXDcTS")?;
        let energy_program_id = Pubkey::from_str("GjSjmPt8VSHr49ti4BijWZSu7rwb8o32pod7gNBnTY4U")?;
        
        let (registry_pda, _) = Pubkey::find_program_address(&[b"registry"], &registry_program_id);
        let (token_info_pda, _) = Pubkey::find_program_address(&[b"token_info_2022"], &energy_program_id);

        // --- TOKEN MINTS ---
        let token_program_id = Pubkey::from_str("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")?;
        let token_program_address = solana_address::Address::from(token_program_id.to_bytes());

        // Initialize Energy Token Mint (GpGDVgksF2ivMv3XXR4VZDXRmW9G6agA2AGkKUBQRzk6)
        let mint_pubkey = Pubkey::from_str("GpGDVgksF2ivMv3XXR4VZDXRmW9G6agA2AGkKUBQRzk6")?;
        let mint_address = solana_address::Address::from(mint_pubkey.to_bytes());
        
        let mut data = vec![0u8; 82];
        data[0..4].copy_from_slice(&1u32.to_le_bytes()); // COption::Some
        data[4..36].copy_from_slice(&token_info_pda.to_bytes()); // Authority MUST be token_info_pda
        data[44] = 9;
        data[45] = 1;
        
        let mint_account = solana_account::Account {
            lamports: 1_000_000_000,
            data,
            owner: token_program_address,
            executable: false,
            rent_epoch: 0,
        };
        let _ = svm.set_account(mint_address, mint_account);
        info!("🪙 Initialized Energy Token Mint in LiteSVM: {}. Authority set to TokenInfo PDA: {}", mint_pubkey, token_info_pda);

        // Initialize Currency Token Mint (8BGFtQLRaY9Nh5BGUwjJvdeXEsscCgJAi5zTgALk1Vg5)
        let currency_pubkey = Pubkey::from_str("8BGFtQLRaY9Nh5BGUwjJvdeXEsscCgJAi5zTgALk1Vg5")?;
        let currency_address = solana_address::Address::from(currency_pubkey.to_bytes());
        
        let mut currency_data = vec![0u8; 82];
        currency_data[0..4].copy_from_slice(&1u32.to_le_bytes()); // COption::Some
        currency_data[4..36].copy_from_slice(&auth_pubkey.to_bytes()); // Admin is okay for currency
        currency_data[44] = 6;
        currency_data[45] = 1;
        
        let currency_account = solana_account::Account {
            lamports: 1_000_000_000,
            data: currency_data,
            owner: token_program_address,
            executable: false,
            rent_epoch: 0,
        };
        let _ = svm.set_account(currency_address, currency_account);
        info!("🪙 Initialized Currency Token Mint in LiteSVM: {}", currency_pubkey);

        // --- REGISTRY ACCOUNTS ---
        let registry_program_address = solana_address::Address::from(registry_program_id.to_bytes());
        let registry_address = solana_address::Address::from(registry_pda.to_bytes());

        let mut registry_data = vec![0u8; 104];
        registry_data[0..8].copy_from_slice(&[47, 174, 110, 246, 184, 182, 252, 218]); // account:Registry
        registry_data[8..40].copy_from_slice(&auth_pubkey.to_bytes());
        let registry_account = solana_account::Account {
            lamports: 1_000_000_000,
            data: registry_data,
            owner: registry_program_address,
            executable: false,
            rent_epoch: 0,
        };
        let _ = svm.set_account(registry_address, registry_account);
        info!("📋 Initialized Registry PDA in LiteSVM: {}", registry_pda);

        let (shard_pda, _) = Pubkey::find_program_address(&[b"registry_shard", &[0u8]], &registry_program_id);
        let shard_address = solana_address::Address::from(shard_pda.to_bytes());
        let mut shard_data = vec![0u8; 32];
        shard_data[0..8].copy_from_slice(&[98, 27, 121, 8, 54, 239, 169, 252]); // account:RegistryShard
        let shard_account = solana_account::Account {
            lamports: 1_000_000_000,
            data: shard_data,
            owner: registry_program_address,
            executable: false,
            rent_epoch: 0,
        };
        let _ = svm.set_account(shard_address, shard_account);
        info!("📋 Initialized RegistryShard 0 in LiteSVM: {}", shard_pda);

        // --- ENERGY TOKEN ACCOUNTS ---
        let energy_program_address = solana_address::Address::from(energy_program_id.to_bytes());
        let token_info_address = solana_address::Address::from(token_info_pda.to_bytes());
        let mut token_info_data = vec![0u8; 320];
        token_info_data[0..8].copy_from_slice(&[109, 162, 52, 125, 77, 166, 37, 202]); // account:TokenInfo
        token_info_data[8..40].copy_from_slice(&auth_pubkey.to_bytes());
        token_info_data[40..72].copy_from_slice(&registry_pda.to_bytes());
        token_info_data[72..104].copy_from_slice(&registry_program_id.to_bytes());
        token_info_data[104..136].copy_from_slice(&mint_pubkey.to_bytes());
        let token_info_account = solana_account::Account {
            lamports: 1_000_000_000,
            data: token_info_data,
            owner: energy_program_address,
            executable: false,
            rent_epoch: 0,
        };
        let _ = svm.set_account(token_info_address, token_info_account);
        info!("📋 Initialized TokenInfo PDA in LiteSVM: {}", token_info_pda);

        Ok(())
    }

    async fn ensure_account(&self, pubkey: &Pubkey) -> Result<(), ClientError> {
        let mut svm = self.svm.write().await;
        let address = solana_address::Address::from(pubkey.to_bytes());
        if svm.get_account(&address).is_none() {
            if let Some(ref client) = self.rpc_client {
                info!("🔍 Cloning account {} from mainnet...", pubkey);
                let account = client.get_account(pubkey).await?;
                let svm_account = solana_account::Account {
                    lamports: account.lamports,
                    data: account.data,
                    owner: solana_address::Address::from(account.owner.to_bytes()),
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                };
                svm.set_account(address, svm_account)
                    .map_err(|e| ClientError::from(solana_client::client_error::ClientErrorKind::Custom(e.to_string())))?;
            }
        }
        Ok(())
    }
}

#[async_trait]
impl SolanaProvider for SurfpoolSolanaProvider {
    async fn simulate_transaction(&self, transaction: &Transaction) -> Result<Response<RpcSimulateTransactionResult>, ClientError> {
        // Ensure all accounts in the transaction are cloned if needed
        for message in &transaction.message.instructions {
            for key_idx in &message.accounts {
                if let Some(key) = transaction.message.account_keys.get(*key_idx as usize) {
                    self.ensure_account(key).await?;
                }
            }
        }

        let svm = self.svm.write().await;
        let sdk_vtx = solana_sdk::transaction::VersionedTransaction::from(transaction.clone());
        let bytes = bincode::serialize(&sdk_vtx).map_err(|e| ClientError::from(solana_client::client_error::ClientErrorKind::Custom(e.to_string())))?;
        let versioned_tx: solana_transaction::versioned::VersionedTransaction = bincode::deserialize(&bytes)
            .map_err(|e| ClientError::from(solana_client::client_error::ClientErrorKind::Custom(e.to_string())))?;
        let result = svm.simulate_transaction(versioned_tx)
            .map_err(|e| ClientError::from(solana_client::client_error::ClientErrorKind::Custom(format!("{:?}", e))))?;
        
        Ok(Response {
            context: solana_client::rpc_response::RpcResponseContext { slot: 0, api_version: None },
            value: RpcSimulateTransactionResult {
                err: None, // If we are here, simulation succeeded
                logs: Some(result.meta.logs.clone()),
                accounts: None,
                units_consumed: Some(result.meta.compute_units_consumed),
                return_data: None,
                inner_instructions: None,
                loaded_accounts_data_size: None,
                replacement_blockhash: None,
            },
        })
    }

    async fn send_transaction(&self, transaction: &Transaction) -> Result<Signature, ClientError> {
        // Ensure payer exists and has SOL before sending in simnet
        if let Some(payer) = transaction.message.account_keys.first() {
             let mut svm = self.svm.write().await;
             let address = solana_address::Address::from(payer.to_bytes());
             let balance = svm.get_balance(&address).unwrap_or(0);
             if balance < 1_000_000_000 {
                 info!("💸 Ensuring payer {} has SOL (current balance: {}). Airdropping 10 SOL...", payer, balance);
                 svm.airdrop(&address, 10_000_000_000)
                     .map_err(|e| ClientError::from(solana_client::client_error::ClientErrorKind::Custom(format!("{:?}", e))))?;
             }
        }

        let mut svm = self.svm.write().await;
        let signature = transaction.signatures.first().cloned().unwrap_or_default();
        
        let sdk_vtx = solana_sdk::transaction::VersionedTransaction::from(transaction.clone());
        let bytes = bincode::serialize(&sdk_vtx).map_err(|e| ClientError::from(solana_client::client_error::ClientErrorKind::Custom(e.to_string())))?;
        let versioned_tx: solana_transaction::versioned::VersionedTransaction = bincode::deserialize(&bytes)
            .map_err(|e| ClientError::from(solana_client::client_error::ClientErrorKind::Custom(e.to_string())))?;

        svm.send_transaction(versioned_tx)
            .map_err(|e| ClientError::from(solana_client::client_error::ClientErrorKind::Custom(format!("{:?}", e))))?;
        
        Ok(signature)
    }


    async fn get_latest_blockhash(&self) -> Result<(Hash, u64), ClientError> {
        let svm = self.svm.read().await;
        let hash = svm.latest_blockhash();
        Ok((Hash::new_from_array(hash.to_bytes()), 1000))
    }

    async fn get_balance(&self, pubkey: &Pubkey) -> Result<u64, ClientError> {
        self.ensure_account(pubkey).await?;
        let svm = self.svm.read().await;
        let address = solana_address::Address::from(pubkey.to_bytes());
        Ok(svm.get_balance(&address).unwrap_or(0))
    }

    async fn get_account(&self, pubkey: &Pubkey) -> Result<Account, ClientError> {
        self.ensure_account(pubkey).await?;
        let svm = self.svm.read().await;
        let address = solana_address::Address::from(pubkey.to_bytes());
        let account = svm.get_account(&address)
            .ok_or_else(|| ClientError::from(solana_client::client_error::ClientErrorKind::Custom("Account not found".to_string())))?;
        
        Ok(Account {
            lamports: account.lamports,
            data: account.data,
            owner: Pubkey::new_from_array(account.owner.to_bytes()),
            executable: account.executable,
            rent_epoch: account.rent_epoch,
        })
    }

    async fn get_recent_prioritization_fees(&self, _pubkeys: &[Pubkey]) -> Result<Vec<RpcPrioritizationFee>, ClientError> {
        Ok(vec![])
    }

    async fn get_token_account_balance(&self, _pubkey: &Pubkey) -> Result<serde_json::Value, ClientError> {
        Ok(serde_json::json!({"amount": "1000000000", "decimals": 9, "uiAmount": 1.0}))
    }

    async fn get_signature_statuses(&self, signatures: &[Signature]) -> Result<Response<Vec<Option<serde_json::Value>>>, ClientError> {
        let values = signatures.iter().map(|_| Some(serde_json::json!({"slot": 0, "confirmations": 1, "err": null, "confirmationStatus": "finalized"}))).collect();
        Ok(Response {
            context: solana_client::rpc_response::RpcResponseContext { slot: 0, api_version: None },
            value: values,
        })
    }

    async fn get_slot(&self) -> Result<u64, ClientError> {
        Ok(0)
    }

    async fn request_airdrop(&self, pubkey: &Pubkey, lamports: u64) -> Result<Signature, ClientError> {
        let mut svm = self.svm.write().await;
        let address = solana_address::Address::from(pubkey.to_bytes());
        svm.airdrop(&address, lamports)
            .map_err(|e| ClientError::from(solana_client::client_error::ClientErrorKind::Custom(format!("{:?}", e))))?;
        Ok(Signature::default())
    }

    async fn get_transaction(&self, _signature: &Signature) -> Result<serde_json::Value, ClientError> {
        Ok(serde_json::json!({}))
    }

    async fn get_epoch_info(&self) -> Result<solana_sdk::epoch_info::EpochInfo, ClientError> {
        Ok(solana_sdk::epoch_info::EpochInfo {
            absolute_slot: 100,
            block_height: 100,
            epoch: 1,
            slots_in_epoch: 432000,
            slot_index: 100,
            transaction_count: Some(1000),
        })
    }
}

use crate::vault::VaultProvider;

pub struct ChainBridgeGrpcService {
    provider: Arc<dyn SolanaProvider>,
    vault: Arc<dyn VaultProvider>,
    blockhash_cache: Arc<BlockhashCache>,
    transit_key_name: String,
}

impl ChainBridgeGrpcService {
    pub fn new(
        provider: Arc<dyn SolanaProvider>, 
        vault: Arc<dyn VaultProvider>,
        blockhash_cache: Arc<BlockhashCache>,
    ) -> Self {
        let transit_key_name = std::env::var("CHAIN_BRIDGE_VAULT_KEY_NAME")
            .unwrap_or_else(|_| "gridtokenx-bridge".to_string());

        Self {
            provider,
            vault,
            blockhash_cache,
            transit_key_name,
        }
    }

    pub fn provider(&self) -> Arc<dyn SolanaProvider> {
        self.provider.clone()
    }

    fn extract_role(&self, ctx: &Context) -> ServiceRole {
        // Primary path: SPIFFE URI from verified TLS client certificate
        // We look for it in headers if we can't get it from extensions easily with connectrpc
        if let Some(spiffe_id) = ctx.headers.get("z-gridtokenx-spiffe-id").and_then(|v| v.to_str().ok()) {
            let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(spiffe_id.to_string());
            let role = ServiceRole::from(&identity);
            info!("mTLS peer verified → identity: {} role: {}", spiffe_id, role);
            return role;
        }

        // Dev-only fallback: trust everything when insecure mode is explicitly enabled
        if std::env::var("CHAIN_BRIDGE_INSECURE").map(|v| v.to_lowercase() == "true").unwrap_or(false) {
            warn!("⚠️ Granting ADMIN role due to CHAIN_BRIDGE_INSECURE mode");
            return ServiceRole::Admin;
        }

        // Dev-only fallback: trust header only when escape hatch env var is set
        if std::env::var("CHAIN_BRIDGE_ALLOW_HEADER_AUTH").is_ok() {
            warn!("⚠️ Using header-based auth (dev mode only)");
            return ServiceRole::from_headers(&ctx.headers);
        }

        ServiceRole::Unknown
    }

    /// Reusable signing and submission logic for both gRPC and NATS
    pub async fn sign_and_submit(&self, serialized_tx: &[u8], key_id: &str, identity: &gridtokenx_blockchain_core::auth::SpiffeIdentity) -> anyhow::Result<(Signature, u64)> {
        let mut transaction: Transaction = bincode::deserialize(serialized_tx)
            .map_err(|e| anyhow::anyhow!("Invalid transaction format: {}", e))?;

        gridtokenx_blockchain_core::policy::PolicyEngine::validate_transaction(identity, &transaction)
            .map_err(|e| anyhow::anyhow!("Policy Engine rejection: {}", e))?;

        if key_id == "platform_admin" {
            // Only set blockhash if it's empty
            if transaction.message.recent_blockhash == solana_sdk::hash::Hash::default() {
                // 1. Refresh blockhash from cache (Wall 1 mitigation in SKILL.md)
                let (bh, _) = match self.blockhash_cache.get().await {
                    Some(cached) => cached,
                    None => {
                        // Fallback to slow path if cache is empty (e.g. at startup)
                        info!("⚠️ Blockhash cache empty, performing slow-path RPC refresh");
                        self.provider.get_latest_blockhash().await
                            .map_err(|e| anyhow::anyhow!("Failed to refresh blockhash: {}", e))?
                    }
                };
                
                transaction.message.recent_blockhash = bh;
            }

            // 2. Sign the message data, not the whole transaction
            let message_data = transaction.message_data();
            let num_required = transaction.message.header.num_required_signatures as usize;
            let account_keys = &transaction.message.account_keys;
            
            info!("📝 Signing transaction for {} required signatures. Payer: {}", num_required, account_keys[0]);
            if num_required > 1 {
                for i in 0..num_required {
                    info!("  Signer {}: {}", i, account_keys[i]);
                }
            }
            
            // 3. Request signature from Vault
            let signature = self.vault.sign_message(&self.transit_key_name, &message_data).await
                .context("Vault Transit signing failed")?;

            // 4. Attach signature at slot 0 (the fee payer slot)
            // Ensure the signatures vector is correctly sized
            if transaction.signatures.len() < num_required {
                transaction.signatures.resize(num_required, Signature::default());
            }
            
            transaction.signatures[0] = signature;

            info!("✅ Transaction signed remotely via Vault Transit for platform_admin. Signature: {}", signature);
        } else if !key_id.is_empty() {
             return Err(anyhow::anyhow!("Key ID not authorized: {}", key_id));
        }

        let sig = self.provider.send_transaction(&transaction).await
            .map_err(|e| anyhow::anyhow!("Solana RPC submission failed: {}", e))?;

        Ok((sig, 0))
    }
}

impl ChainBridgeService for ChainBridgeGrpcService {
    async fn simulate_transaction(
        &self,
        ctx: Context,
        request: OwnedView<SimulateTransactionRequestView<'static>>,
    ) -> Result<(SimulateTransactionResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[ServiceRole::TradingApi, ServiceRole::TradingMatcher, ServiceRole::OracleBridge, ServiceRole::IamService, ServiceRole::Admin])
            .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received simulate_transaction request for key_id: {}", request.key_id);
        
        let tx: Transaction = bincode::deserialize(&request.serialized_transaction)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, format!("Invalid transaction format: {}", e)))?;

        match self.provider.simulate_transaction(&tx).await {
            Ok(resp) => {
                let mut response = SimulateTransactionResponse::default();
                response.success = resp.value.err.is_none();
                response.compute_units_consumed = resp.value.units_consumed.unwrap_or(0);
                response.logs = resp.value.logs.unwrap_or_default();
                Ok((response, ctx))
            }
            Err(e) => {
                error!("Solana RPC simulate error: {}", e);
                Err(ConnectError::new(ErrorCode::Internal, "Solana RPC simulation failed"))
            }
        }
    }

    async fn submit_transaction(
        &self,
        ctx: Context,
        request: OwnedView<SubmitTransactionRequestView<'static>>,
    ) -> Result<(SubmitTransactionResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[ServiceRole::TradingApi, ServiceRole::TradingMatcher, ServiceRole::OracleBridge, ServiceRole::IamService, ServiceRole::Admin])
            .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received submit_transaction request with key_id: {}", request.key_id);
        
        let identity_str = ctx.headers.get("z-gridtokenx-spiffe-id")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("unknown");
        let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(identity_str.to_string());

        let result = self.sign_and_submit(&request.serialized_transaction, &request.key_id, &identity).await;

        match result {
            Ok((sig, slot)) => {
                let mut response = SubmitTransactionResponse::default();
                response.success = true;
                response.signature = sig.to_string();
                response.error_message = String::new();
                response.slot = slot;
                Ok((response, ctx))
            }
            Err(e) => {
                let err_msg = format!("{:#}", e);
                error!("Transaction submission failed: {}", err_msg);
                
                let (code, msg) = if err_msg.contains("authorized") {
                    (ErrorCode::PermissionDenied, "Key ID not authorized")
                } else if err_msg.contains("format") {
                    (ErrorCode::InvalidArgument, "Invalid transaction format")
                } else {
                    (ErrorCode::Internal, "Transaction submission failed")
                };
                Err(ConnectError::new(code, msg))
            }
        }
    }

    async fn get_balance(
        &self,
        ctx: Context,
        request: OwnedView<GetBalanceRequestView<'static>>,
    ) -> Result<(GetBalanceResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway, 
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_balance for {}", request.pubkey);
        
        let pubkey = Pubkey::from_str(&request.pubkey)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, format!("Invalid pubkey: {}", e)))?;

        match self.provider.get_balance(&pubkey).await {
            Ok(lamports) => {
                let mut response = GetBalanceResponse::default();
                response.lamports = lamports;
                Ok((response, ctx))
            }
            Err(e) => {
                error!("Solana RPC get_balance error for {}: {}", request.pubkey, e);
                Err(ConnectError::new(ErrorCode::Internal, "Failed to fetch balance"))
            }
        }
    }

    async fn get_account_data(
        &self,
        ctx: Context,
        request: OwnedView<GetAccountDataRequestView<'static>>,
    ) -> Result<(GetAccountDataResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway, 
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_account_data for {}", request.pubkey);
        
        let pubkey = Pubkey::from_str(&request.pubkey)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, format!("Invalid pubkey: {}", e)))?;

        match self.provider.get_account(&pubkey).await {
            Ok(account) => {
                let mut response = GetAccountDataResponse::default();
                response.exists = true;
                response.data = account.data;
                Ok((response, ctx))
            }
            Err(e) => {
                if e.to_string().contains("AccountNotFound") {
                     let mut response = GetAccountDataResponse::default();
                     response.exists = false;
                     response.data = vec![];
                     Ok((response, ctx))
                } else {
                    error!("Solana RPC get_account error for {}: {}", request.pubkey, e);
                    Err(ConnectError::new(ErrorCode::Internal, "Failed to fetch account data"))
                }
            }
        }
    }

    async fn get_latest_blockhash(
        &self,
        ctx: Context,
        _request: OwnedView<GetLatestBlockhashRequestView<'static>>,
    ) -> Result<(GetLatestBlockhashResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_latest_blockhash");
        
        match self.provider.get_latest_blockhash().await {
            Ok((blockhash, last_valid_block_height)) => {
                let mut response = GetLatestBlockhashResponse::default();
                response.blockhash = blockhash.to_string();
                response.last_valid_block_height = last_valid_block_height;
                Ok((response, ctx))
            }
            Err(e) => {
                error!("Solana RPC get_latest_blockhash error: {}", e);
                Err(ConnectError::new(ErrorCode::Internal, "Failed to fetch blockhash"))
            }
        }
    }

    async fn get_recent_prioritization_fees(
        &self,
        ctx: Context,
        request: OwnedView<GetRecentPrioritizationFeesRequestView<'static>>,
    ) -> Result<(GetRecentPrioritizationFeesResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_recent_prioritization_fees for {} accounts", request.account_keys.len());
        
        let account_keys: Vec<Pubkey> = request.account_keys.iter()
            .map(|k| Pubkey::from_str(k).map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, format!("Invalid account key '{}': {}", k, e))))
            .collect::<Result<Vec<_>, _>>()?;

        match self.provider.get_recent_prioritization_fees(&account_keys).await {
            Ok(fees) => {
                let mut response = GetRecentPrioritizationFeesResponse::default();
                response.fees = fees.into_iter().map(|f| {
                    let mut fee = PrioritizationFee::default();
                    fee.slot = f.slot;
                    fee.prioritization_fee = f.prioritization_fee;
                    fee
                }).collect();
                Ok((response, ctx))
            }
            Err(e) => {
                error!("Solana RPC get_recent_prioritization_fees error: {}", e);
                Err(ConnectError::new(ErrorCode::Internal, "Failed to fetch prioritization fees"))
            }
        }
    }

    async fn get_token_account_balance(
        &self,
        ctx: Context,
        request: OwnedView<GetTokenAccountBalanceRequestView<'static>>,
    ) -> Result<(GetTokenAccountBalanceResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway, 
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_token_account_balance for {}", request.pubkey);
        
        let pubkey = Pubkey::from_str(&request.pubkey)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, format!("Invalid pubkey: {}", e)))?;

        match self.provider.get_token_account_balance(&pubkey).await {
            Ok(balance) => {
                let mut response = GetTokenAccountBalanceResponse::default();
                response.amount = balance["amount"].as_str().unwrap_or("0").to_string();
                response.decimals = balance["decimals"].as_u64().unwrap_or(0) as u32;
                response.ui_amount = balance["ui_amount"].as_f64().unwrap_or(0.0);
                Ok((response, ctx))
            }
            Err(e) => {
                error!("Solana RPC get_token_account_balance error for {}: {}", request.pubkey, e);
                Err(ConnectError::new(ErrorCode::Internal, "Failed to fetch token balance"))
            }
        }
    }

    async fn get_signature_status(
        &self,
        ctx: Context,
        request: OwnedView<GetSignatureStatusRequestView<'static>>,
    ) -> Result<(GetSignatureStatusResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway, 
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_signature_status for {}", request.signature);
        
        let signature = Signature::from_str(&request.signature)
            .map_err(|e: solana_sdk::signature::ParseSignatureError| ConnectError::new(ErrorCode::InvalidArgument, format!("Invalid signature: {}", e)))?;

        match self.provider.get_signature_statuses(&[signature]).await {
            Ok(resp) => {
                if let Some(Some(status)) = resp.value.first() {
                    let mut response = GetSignatureStatusResponse::default();
                    response.confirmed = status["confirmations"].as_u64().is_some() || status["err"].is_null();
                    response.status = status["confirmation_status"].as_str().unwrap_or("Unknown").to_string();
                    response.error = if status["err"].is_null() { "".to_string() } else { status["err"].to_string() };
                    Ok((response, ctx))
                } else {
                    let mut response = GetSignatureStatusResponse::default();
                    response.confirmed = false;
                    response.status = "NotFound".to_string();
                    Ok((response, ctx))
                }
            }
            Err(e) => {
                error!("Solana RPC get_signature_statuses error: {}", e);
                Err(ConnectError::new(ErrorCode::Internal, "Failed to fetch signature status"))
            }
        }
    }

    async fn get_slot(
        &self,
        ctx: Context,
        _request: OwnedView<GetSlotRequestView<'static>>,
    ) -> Result<(GetSlotResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_slot");
        
        match self.provider.get_slot().await {
            Ok(slot) => {
                let mut response = GetSlotResponse::default();
                response.slot = slot;
                Ok((response, ctx))
            }
            Err(e) => {
                error!("Solana RPC get_slot error: {}", e);
                Err(ConnectError::new(ErrorCode::Internal, "Failed to fetch current slot"))
            }
        }
    }

    async fn request_airdrop(
        &self,
        ctx: Context,
        request: OwnedView<chain_v1::RequestAirdropRequestView<'static>>,
    ) -> Result<(chain_v1::RequestAirdropResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[ServiceRole::Admin, ServiceRole::IamService])
            .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received request_airdrop for {} ({} lamports)", request.pubkey, request.lamports);
        
        let pubkey = Pubkey::from_str(&request.pubkey)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, format!("Invalid pubkey: {}", e)))?;

        match self.provider.request_airdrop(&pubkey, request.lamports).await {
            Ok(sig) => {
                let mut response = chain_v1::RequestAirdropResponse::default();
                response.success = true;
                response.signature = sig.to_string();
                Ok((response, ctx))
            }
            Err(e) => {
                error!("Solana RPC request_airdrop error: {}", e);
                Err(ConnectError::new(ErrorCode::Internal, "Airdrop request failed"))
            }
        }
    }

    async fn get_transaction_details(
        &self,
        ctx: Context,
        request: OwnedView<chain_v1::GetTransactionDetailsRequestView<'static>>,
    ) -> Result<(chain_v1::GetTransactionDetailsResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway, 
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_transaction_details for {}", request.signature);
        
        let signature = Signature::from_str(&request.signature)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, format!("Invalid signature: {}", e)))?;

        match self.provider.get_transaction(&signature).await {
            Ok(tx_val) => {
                let mut response = chain_v1::GetTransactionDetailsResponse::default();
                response.found = true;
                response.slot = tx_val["slot"].as_u64().unwrap_or(0);
                // Extract account keys if possible
                if let Some(accounts) = tx_val["transaction"]["message"]["accountKeys"].as_array() {
                    response.account_keys = accounts.iter().map(|v| v.as_str().unwrap_or("").to_string()).collect();
                }
                Ok((response, ctx))
            }
            Err(e) => {
                if e.to_string().contains("TransactionNotFound") || e.to_string().contains("not found") {
                    let mut response = chain_v1::GetTransactionDetailsResponse::default();
                    response.found = false;
                    Ok((response, ctx))
                } else {
                    error!("Solana RPC get_transaction error: {}", e);
                    Err(ConnectError::new(ErrorCode::Internal, "Failed to fetch transaction details"))
                }
            }
        }
    }

    async fn get_epoch_info(
        &self,
        ctx: Context,
        _request: OwnedView<chain_v1::GetEpochInfoRequestView<'static>>,
    ) -> Result<(chain_v1::GetEpochInfoResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway,
            ServiceRole::TradingApi,
            ServiceRole::TradingMatcher,
            ServiceRole::OracleBridge,
            ServiceRole::IamService,
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_epoch_info");

        match self.provider.get_epoch_info().await {
            Ok(info) => {
                let mut response = chain_v1::GetEpochInfoResponse::default();
                response.epoch = info.epoch;
                response.slot = info.absolute_slot;
                Ok((response, ctx))
            }
            Err(e) => {
                error!("Solana RPC get_epoch_info error: {}", e);
                Err(ConnectError::new(ErrorCode::Internal, "Failed to fetch epoch info"))
            }
        }
    }

}

#[cfg(test)]
mod tests {
    use super::*;
    use solana_sdk::signature::{Keypair, Signer};
    use solana_client::rpc_response::{Response, RpcResponseContext, RpcSimulateTransactionResult};
    use buffa::view::OwnedView;
    use connectrpc::{Context, ErrorCode};

    struct MockSolanaProvider;

    #[async_trait]
    impl SolanaProvider for MockSolanaProvider {
        async fn simulate_transaction(&self, _transaction: &Transaction) -> Result<Response<RpcSimulateTransactionResult>, ClientError> {
            Ok(Response {
                context: RpcResponseContext { slot: 100, api_version: None },
                value: RpcSimulateTransactionResult {
                    err: None,
                    logs: Some(vec!["Program log: Hello".to_string()]),
                    accounts: None,
                    units_consumed: Some(100),
                    return_data: None,
                    inner_instructions: None,
                    loaded_accounts_data_size: None,
                    replacement_blockhash: None,
                },
            })
        }
        async fn send_transaction(&self, _transaction: &Transaction) -> Result<Signature, ClientError> {
            Ok(Signature::from([0u8; 64]))
        }
        async fn get_latest_blockhash(&self) -> Result<(Hash, u64), ClientError> {
            Ok((Hash::default(), 1000))
        }
        async fn get_balance(&self, _pubkey: &Pubkey) -> Result<u64, ClientError> {
            Ok(1000000000) // 1 SOL
        }
        async fn get_account(&self, _pubkey: &Pubkey) -> Result<Account, ClientError> {
            Ok(Account {
                lamports: 1000000000,
                data: vec![1, 2, 3],
                owner: Pubkey::default(),
                executable: false,
                rent_epoch: 0,
            })
        }
        async fn get_recent_prioritization_fees(&self, _pubkeys: &[Pubkey]) -> Result<Vec<RpcPrioritizationFee>, ClientError> {
            Ok(vec![RpcPrioritizationFee {
                slot: 100,
                prioritization_fee: 1000,
            }])
        }
        async fn get_token_account_balance(&self, _pubkey: &Pubkey) -> Result<serde_json::Value, ClientError> {
            Ok(serde_json::json!({
                "ui_amount": 10.5,
                "decimals": 9,
                "amount": "10500000000",
                "ui_amount_string": "10.5"
            }))
        }
        async fn get_signature_statuses(&self, _signatures: &[Signature]) -> Result<Response<Vec<Option<serde_json::Value>>>, ClientError> {
            Ok(Response {
                context: RpcResponseContext { slot: 101, api_version: None },
                value: vec![Some(serde_json::json!({
                    "slot": 100,
                    "confirmations": 31,
                    "err": null,
                    "confirmation_status": "Confirmed"
                }))],
            })
        }
        async fn get_slot(&self) -> Result<u64, ClientError> {
            Ok(100)
        }
        async fn request_airdrop(&self, _pubkey: &Pubkey, _lamports: u64) -> Result<Signature, ClientError> {
            Ok(Signature::from([0u8; 64]))
        }
        async fn get_transaction(&self, _signature: &Signature) -> Result<serde_json::Value, ClientError> {
            Ok(serde_json::json!({
                "slot": 100,
                "transaction": {
                    "message": {
                        "accountKeys": ["11111111111111111111111111111111"]
                    }
                }
            }))
        }
        async fn get_epoch_info(&self) -> Result<solana_sdk::epoch_info::EpochInfo, ClientError> {
            Ok(solana_sdk::epoch_info::EpochInfo {
                absolute_slot: 100,
                block_height: 100,
                epoch: 1,
                slots_in_epoch: 432000,
                slot_index: 100,
                transaction_count: Some(1000),
            })
        }
    }

    struct MockVaultProvider;

    #[async_trait]
    impl VaultProvider for MockVaultProvider {
        async fn get_public_key(&self, _key_name: &str) -> anyhow::Result<Pubkey> {
            Ok(Pubkey::default())
        }
        async fn sign_message(&self, _key_name: &str, _message: &[u8]) -> anyhow::Result<Signature> {
            Ok(Signature::from([0u8; 64]))
        }
    }

    fn create_test_service() -> ChainBridgeGrpcService {
        ChainBridgeGrpcService {
            provider: Arc::new(MockSolanaProvider {}),
            vault: Arc::new(MockVaultProvider),
            blockhash_cache: Arc::new(BlockhashCache::new()),
            transit_key_name: "test-key".to_string(),
        }
    }

    fn authenticated_ctx() -> Context {
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/admin".parse().unwrap());
        ctx
    }

    #[tokio::test]
    async fn test_get_balance() {
        let service = create_test_service();
        let pubkey = Pubkey::new_unique();
        let mut request_owned = GetBalanceRequest::default();
        request_owned.pubkey = pubkey.to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_balance(authenticated_ctx(), request).await.unwrap();
        assert_eq!(resp.lamports, 1000000000);
    }

    #[tokio::test]
    async fn test_simulate_transaction() {
        let service = create_test_service();
        let from = Keypair::new();
        let to = Pubkey::new_unique();
        let ix = solana_sdk::system_instruction::transfer(&from.pubkey(), &to, 1000);
        let tx = Transaction::new_with_payer(&[ix], Some(&from.pubkey()));
        let serialized_tx = bincode::serialize(&tx).unwrap();

        let mut request_owned = SimulateTransactionRequest::default();
        request_owned.serialized_transaction = serialized_tx;
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.simulate_transaction(authenticated_ctx(), request).await.unwrap();
        assert!(resp.success);
        assert_eq!(resp.compute_units_consumed, 100);
        assert_eq!(resp.logs[0], "Program log: Hello");
    }

    #[tokio::test]
    async fn test_submit_transaction_with_platform_admin() {
        let service = create_test_service();
        let to = Pubkey::new_unique();
        let ix = solana_sdk::system_instruction::transfer(&Pubkey::default(), &to, 1000);
        let tx = Transaction::new_with_payer(&[ix], Some(&Pubkey::default()));
        let serialized_tx = bincode::serialize(&tx).unwrap();

        let mut request_owned = SubmitTransactionRequest::default();
        request_owned.serialized_transaction = serialized_tx;
        request_owned.key_id = "platform_admin".to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.submit_transaction(authenticated_ctx(), request).await.unwrap();
        assert!(resp.success);
        assert!(!resp.signature.is_empty());
    }

    fn unauthenticated_ctx() -> Context {
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/guest".parse().unwrap());
        ctx
    }

    #[tokio::test]
    async fn test_submit_transaction_unauthorized() {
        let service = create_test_service();
        let mut request_owned = SubmitTransactionRequest::default();
        request_owned.key_id = "unknown_user".to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let result = service.submit_transaction(unauthenticated_ctx(), request).await;
        assert!(result.is_err());
        assert_eq!(result.err().unwrap().code, ErrorCode::PermissionDenied);
    }

    #[tokio::test]
    async fn test_get_account_data_exists() {
        let service = create_test_service();
        let mut request_owned = GetAccountDataRequest::default();
        request_owned.pubkey = Pubkey::new_unique().to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_account_data(authenticated_ctx(), request).await.unwrap();
        assert!(resp.exists);
        assert_eq!(resp.data, vec![1, 2, 3]);
    }

    #[tokio::test]
    async fn test_get_epoch_info() {
        let service = create_test_service();
        let request_owned = chain_v1::GetEpochInfoRequest::default();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_epoch_info(authenticated_ctx(), request).await.unwrap();
        assert_eq!(resp.epoch, 1);
        assert_eq!(resp.slot, 100);
    }

    #[tokio::test]
    async fn test_blockhash_cache() {
        let cache = BlockhashCache::new();
        assert!(cache.get().await.is_none());

        let hash = Hash::new_unique();
        cache.update(hash, 1000).await;

        let cached = cache.get().await.unwrap();
        assert_eq!(cached.0, hash);
        assert_eq!(cached.1, 1000);
    }

    #[tokio::test]
    async fn test_blockhash_cache_overwrite() {
        let cache = BlockhashCache::new();
        let hash1 = Hash::new_unique();
        let hash2 = Hash::new_unique();

        cache.update(hash1, 1000).await;
        cache.update(hash2, 2000).await;

        let cached = cache.get().await.unwrap();
        assert_eq!(cached.0, hash2);
        assert_eq!(cached.1, 2000);
    }

    #[tokio::test]
    async fn test_blockhash_cache_concurrent() {
        let cache = Arc::new(BlockhashCache::new());
        let cache_clone = cache.clone();

        let hash = Hash::new_unique();
        
        let handle = tokio::spawn(async move {
            cache_clone.update(hash, 1000).await;
        });

        let _ = cache.get().await;
        handle.await.unwrap();
        
        let cached = cache.get().await.unwrap();
        assert_eq!(cached.0, hash);
    }

    // ---------------------------------------------------------------
    // sign_and_submit branch coverage
    // ---------------------------------------------------------------

    #[tokio::test]
    async fn test_sign_and_submit_empty_cache_fallback() {
        let service = create_test_service();
        // Cache is empty by default

        let to = Pubkey::new_unique();
        let ix = solana_sdk::system_instruction::transfer(&Pubkey::default(), &to, 1000);
        let tx = Transaction::new_with_payer(&[ix], Some(&Pubkey::default()));
        let serialized = bincode::serialize(&tx).unwrap();

        let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(
            "spiffe://gridtokenx.th/prod/admin".to_string()
        );

        // Should fallback to MockSolanaProvider which returns Hash::default()
        let result = service.sign_and_submit(&serialized, "platform_admin", &identity).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_sign_and_submit_multi_sig() {
        let service = create_test_service();
        
        let from1 = Pubkey::new_unique();
        let from2 = Pubkey::new_unique();
        let to = Pubkey::new_unique();
        
        let ix = solana_sdk::system_instruction::transfer(&from1, &to, 1000);
        let mut msg = solana_sdk::message::Message::new(&[ix], Some(&from1));
        // Add second required signer manually
        msg.header.num_required_signatures = 2;
        msg.account_keys.insert(1, from2);
        
        let tx = Transaction::new_unsigned(msg);
        let serialized = bincode::serialize(&tx).unwrap();

        let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(
            "spiffe://gridtokenx.th/prod/admin".to_string()
        );

        let result = service.sign_and_submit(&serialized, "platform_admin", &identity).await;
        assert!(result.is_ok());
        // MockVaultProvider returns Signature::from([0u8; 64]) for slot 0
    }

    #[tokio::test]
    async fn test_sign_and_submit_preserves_non_empty_blockhash() {
        let service = create_test_service();

        // Pre-populate cache with a blockhash
        let cached_hash = Hash::new_unique();
        service.blockhash_cache.update(cached_hash, 9999).await;

        // Create a tx with a non-default blockhash
        let custom_hash = Hash::new_unique();
        let to = Pubkey::new_unique();
        let ix = solana_sdk::system_instruction::transfer(&Pubkey::default(), &to, 1000);
        let mut tx = Transaction::new_with_payer(&[ix], Some(&Pubkey::default()));
        tx.message.recent_blockhash = custom_hash;

        let serialized = bincode::serialize(&tx).unwrap();
        let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(
            "spiffe://gridtokenx.th/prod/admin".to_string()
        );

        let result = service.sign_and_submit(&serialized, "platform_admin", &identity).await;
        assert!(result.is_ok(), "Should succeed with non-empty blockhash");

        // Verify the mock received the transaction — the blockhash should NOT be the cached one
        // (We can't inspect the tx passed to the mock, but the fact it succeeded proves the path works)
    }

    #[tokio::test]
    async fn test_sign_and_submit_invalid_serialized_tx() {
        let service = create_test_service();
        let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(
            "spiffe://gridtokenx.th/prod/admin".to_string()
        );

        let result = service.sign_and_submit(&[0xFF, 0xFE, 0xFD], "platform_admin", &identity).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("Invalid transaction format"));
    }

    #[tokio::test]
    async fn test_sign_and_submit_unauthorized_key_id() {
        let service = create_test_service();
        let to = Pubkey::new_unique();
        let ix = solana_sdk::system_instruction::transfer(&Pubkey::default(), &to, 1000);
        let tx = Transaction::new_with_payer(&[ix], Some(&Pubkey::default()));
        let serialized = bincode::serialize(&tx).unwrap();

        let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(
            "spiffe://gridtokenx.th/prod/admin".to_string()
        );

        let result = service.sign_and_submit(&serialized, "rogue_key", &identity).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("not authorized"));
    }

    #[tokio::test]
    async fn test_sign_and_submit_policy_rejects_unauthorized_program() {
        let service = create_test_service();
        let config = gridtokenx_blockchain_core::config::SolanaProgramsConfig::default();
        let oracle_program_id: Pubkey = config.oracle_program_id.parse().unwrap();

        // Trading identity should not be allowed to call Oracle program
        let ix = solana_sdk::instruction::Instruction {
            program_id: oracle_program_id,
            accounts: vec![],
            data: vec![],
        };
        let tx = Transaction::new_with_payer(&[ix], Some(&Pubkey::default()));
        let serialized = bincode::serialize(&tx).unwrap();

        let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(
            "spiffe://gridtokenx.th/prod/trading-service/matcher".to_string()
        );

        let result = service.sign_and_submit(&serialized, "platform_admin", &identity).await;
        assert!(result.is_err(), "Policy Engine should reject trading-service calling oracle program");
        assert!(result.unwrap_err().to_string().contains("Policy Engine"));
    }

    #[tokio::test]
    async fn test_sign_and_submit_empty_key_id_passes_unsigned() {
        // When key_id is empty, tx is sent unsigned (no signing, no policy check on key)
        // but PolicyEngine still runs
        let service = create_test_service();
        let to = Pubkey::new_unique();
        let ix = solana_sdk::system_instruction::transfer(&Pubkey::default(), &to, 1000);
        let tx = Transaction::new_with_payer(&[ix], Some(&Pubkey::default()));
        let serialized = bincode::serialize(&tx).unwrap();

        let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(
            "spiffe://gridtokenx.th/prod/admin".to_string()
        );

        // Empty key_id should not sign but should still send
        let result = service.sign_and_submit(&serialized, "", &identity).await;
        assert!(result.is_ok(), "Empty key_id should skip signing and send unsigned");
    }

    // ---------------------------------------------------------------
    // Missing gRPC handler tests
    // ---------------------------------------------------------------

    #[tokio::test]
    async fn test_get_latest_blockhash() {
        let service = create_test_service();
        let request_owned = chain_v1::GetLatestBlockhashRequest::default();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_latest_blockhash(authenticated_ctx(), request).await.unwrap();
        // MockSolanaProvider returns Hash::default() and height 1000
        assert_eq!(resp.last_valid_block_height, 1000);
    }

    #[tokio::test]
    async fn test_get_recent_prioritization_fees() {
        let service = create_test_service();
        let mut request_owned = chain_v1::GetRecentPrioritizationFeesRequest::default();
        request_owned.account_keys = vec![Pubkey::default().to_string()];
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_recent_prioritization_fees(authenticated_ctx(), request).await.unwrap();
        assert_eq!(resp.fees.len(), 1);
        assert_eq!(resp.fees[0].prioritization_fee, 1000);
    }

    #[tokio::test]
    async fn test_get_token_account_balance() {
        let service = create_test_service();
        let mut request_owned = chain_v1::GetTokenAccountBalanceRequest::default();
        request_owned.pubkey = Pubkey::new_unique().to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_token_account_balance(authenticated_ctx(), request).await.unwrap();
        assert_eq!(resp.amount, "10500000000");
        assert_eq!(resp.decimals, 9);
    }

    #[tokio::test]
    async fn test_get_signature_status() {
        let service = create_test_service();
        let mut request_owned = chain_v1::GetSignatureStatusRequest::default();
        request_owned.signature = Signature::from([0u8; 64]).to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_signature_status(authenticated_ctx(), request).await.unwrap();
        assert!(resp.confirmed);
        assert_eq!(resp.status, "Confirmed");
    }

    #[tokio::test]
    async fn test_get_slot() {
        let service = create_test_service();
        let request_owned = chain_v1::GetSlotRequest::default();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_slot(authenticated_ctx(), request).await.unwrap();
        assert_eq!(resp.slot, 100);
    }

    #[tokio::test]
    async fn test_request_airdrop_admin_allowed() {
        let service = create_test_service();
        let mut request_owned = chain_v1::RequestAirdropRequest::default();
        request_owned.pubkey = Pubkey::new_unique().to_string();
        request_owned.lamports = 1_000_000_000;
        let request = OwnedView::from_owned(&request_owned).unwrap();

        // Admin should be allowed
        let (resp, _) = service.request_airdrop(authenticated_ctx(), request).await.unwrap();
        assert!(!resp.signature.is_empty());
    }

    #[tokio::test]
    async fn test_request_airdrop_trading_service_denied() {
        let service = create_test_service();
        let mut request_owned = chain_v1::RequestAirdropRequest::default();
        request_owned.pubkey = Pubkey::new_unique().to_string();
        request_owned.lamports = 1_000_000_000;
        let request = OwnedView::from_owned(&request_owned).unwrap();

        // Trading API should be denied
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/trading-service/api".parse().unwrap());

        let result = service.request_airdrop(ctx, request).await;
        assert!(result.is_err(), "Trading service should not be allowed to airdrop");
        assert_eq!(result.err().unwrap().code, ErrorCode::PermissionDenied);
    }

    #[tokio::test]
    async fn test_get_transaction_details() {
        let service = create_test_service();
        let mut request_owned = chain_v1::GetTransactionDetailsRequest::default();
        request_owned.signature = Signature::from([0u8; 64]).to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_transaction_details(authenticated_ctx(), request).await.unwrap();
        assert!(resp.found);
    }

    // ---------------------------------------------------------------
    // extract_role branch coverage
    // ---------------------------------------------------------------

    #[tokio::test]
    async fn test_extract_role_trading_matcher() {
        let service = create_test_service();
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/trading-service/matcher".parse().unwrap());

        // Should be able to submit — TradingMatcher is in the allowed list
        let request_owned = chain_v1::GetSlotRequest::default();
        let request = OwnedView::from_owned(&request_owned).unwrap();
        let (resp, _) = service.get_slot(ctx, request).await.unwrap();
        assert_eq!(resp.slot, 100);
    }

    #[tokio::test]
    async fn test_extract_role_api_gateway_denied_submit() {
        let service = create_test_service();
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/apisix".parse().unwrap());

        // ApiGateway should be denied on SubmitTransaction
        let mut request_owned = SubmitTransactionRequest::default();
        request_owned.key_id = "platform_admin".to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let result = service.submit_transaction(ctx, request).await;
        assert!(result.is_err(), "ApiGateway should be denied write operations");
        assert_eq!(result.err().unwrap().code, ErrorCode::PermissionDenied);
    }

    #[tokio::test]
    async fn test_extract_role_api_gateway_allowed_read() {
        let service = create_test_service();
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/apisix".parse().unwrap());

        // ApiGateway should be allowed on read operations like GetBalance
        let mut request_owned = GetBalanceRequest::default();
        request_owned.pubkey = Pubkey::new_unique().to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_balance(ctx, request).await.unwrap();
        assert_eq!(resp.lamports, 1000000000);
    }

    #[tokio::test]
    async fn test_extract_role_env_overrides() {
        let service = create_test_service();
        
        // 1. Insecure mode override
        {
            let ctx = Context::default();
            unsafe { std::env::set_var("CHAIN_BRIDGE_INSECURE", "true"); }
            let role = service.extract_role(&ctx);
            unsafe { std::env::remove_var("CHAIN_BRIDGE_INSECURE"); }
            assert_eq!(role, ServiceRole::Admin, "Insecure mode should grant Admin");
        }

        // 2. Header auth override
        {
            let mut ctx = Context::default();
            ctx.headers.insert("x-gridtokenx-role", "trading-matcher".parse().unwrap());
            unsafe { std::env::set_var("CHAIN_BRIDGE_ALLOW_HEADER_AUTH", "true"); }
            let role = service.extract_role(&ctx);
            unsafe { std::env::remove_var("CHAIN_BRIDGE_ALLOW_HEADER_AUTH"); }
            assert_eq!(role, ServiceRole::TradingMatcher, "Header auth should grant TradingMatcher");
        }
    }

    #[tokio::test]
    async fn test_get_balance_unauthorized_unknown() {
        let service = create_test_service();
        let ctx = Context::default(); // No SPIFFE header -> Unknown role

        let mut request_owned = chain_v1::GetBalanceRequest::default();
        request_owned.pubkey = Pubkey::new_unique().to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let result = service.get_balance(ctx, request).await;
        assert!(result.is_err());
        assert_eq!(result.err().unwrap().code, ErrorCode::PermissionDenied);
    }

    #[tokio::test]
    async fn test_simulate_transaction_unauthorized_gateway() {
        let service = create_test_service();
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/apisix".parse().unwrap());

        let mut request_owned = chain_v1::SimulateTransactionRequest::default();
        request_owned.key_id = "platform_admin".to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let result = service.simulate_transaction(ctx, request).await;
        assert!(result.is_err());
        assert_eq!(result.err().unwrap().code, ErrorCode::PermissionDenied);
    }

    #[tokio::test]
    async fn test_get_latest_blockhash_unauthorized_gateway() {
        let service = create_test_service();
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/apisix".parse().unwrap());

        let request_owned = chain_v1::GetLatestBlockhashRequest::default();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let result = service.get_latest_blockhash(ctx, request).await;
        assert!(result.is_err());
        assert_eq!(result.err().unwrap().code, ErrorCode::PermissionDenied);
    }

    #[tokio::test]
    async fn test_get_slot_unauthorized_gateway() {
        let service = create_test_service();
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/apisix".parse().unwrap());

        let request_owned = chain_v1::GetSlotRequest::default();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let result = service.get_slot(ctx, request).await;
        assert!(result.is_err());
        assert_eq!(result.err().unwrap().code, ErrorCode::PermissionDenied);
    }
}
