use connectrpc::{Context, ConnectError, ErrorCode};
use anyhow::Context as _;
use buffa::view::OwnedView;
use tracing::{info, error, warn};
use gridtokenx_blockchain_core::auth::ServiceRole;

// Generated code from proto
#[allow(clippy::module_inception)]
pub mod chain_v1 {
    include!(concat!(env!("OUT_DIR"), "/_chain_bridge_include.rs"));
    pub use gridtokenx::chain::v1::*;
}

// Ensure these imports match what is generated by `buffa` mapped from `chain_bridge.proto`.
use chain_v1::{
    ChainBridgeService,
    GetBalanceRequest, GetBalanceRequestView, GetBalanceResponse,
    GetAccountDataRequest, GetAccountDataRequestView, GetAccountDataResponse,
    GetLatestBlockhashRequest, GetLatestBlockhashRequestView, GetLatestBlockhashResponse,
    GetRecentPrioritizationFeesRequest, GetRecentPrioritizationFeesRequestView, GetRecentPrioritizationFeesResponse,
    GetTokenAccountBalanceRequest, GetTokenAccountBalanceRequestView, GetTokenAccountBalanceResponse,
    GetSignatureStatusRequest, GetSignatureStatusRequestView, GetSignatureStatusResponse,
    GetSlotRequest, GetSlotRequestView, GetSlotResponse,
    SimulateTransactionRequest, SimulateTransactionRequestView, SimulateTransactionResponse,
    SubmitTransactionRequest, SubmitTransactionRequestView, SubmitTransactionResponse,
    PrioritizationFee,
};

use solana_client::rpc_client::RpcClient;
use solana_client::client_error::ClientError;
use solana_sdk::account::Account;
use solana_sdk::hash::Hash;
use solana_sdk::signature::Signature;
use solana_client::rpc_response::{Response, RpcSimulateTransactionResult, RpcPrioritizationFee};
use std::str::FromStr;
use solana_sdk::pubkey::Pubkey;
use solana_sdk::transaction::Transaction;
use std::sync::Arc;
use async_trait::async_trait;

/// Abstraction layer for Solana RPC interactions to enable mocking in tests.
#[async_trait]
pub trait SolanaProvider: Send + Sync {
    fn simulate_transaction(&self, transaction: &Transaction) -> Result<Response<RpcSimulateTransactionResult>, ClientError>;
    fn send_transaction(&self, transaction: &Transaction) -> Result<Signature, ClientError>;
    fn get_latest_blockhash(&self) -> Result<(Hash, u64), ClientError>;
    fn get_balance(&self, pubkey: &Pubkey) -> Result<u64, ClientError>;
    fn get_account(&self, pubkey: &Pubkey) -> Result<Account, ClientError>;
    fn get_recent_prioritization_fees(&self, pubkeys: &[Pubkey]) -> Result<Vec<RpcPrioritizationFee>, ClientError>;
    fn get_token_account_balance(&self, pubkey: &Pubkey) -> Result<serde_json::Value, ClientError>;
    fn get_signature_statuses(&self, signatures: &[Signature]) -> Result<Response<Vec<Option<serde_json::Value>>>, ClientError>;
    fn get_slot(&self) -> Result<u64, ClientError>;
}

/// Real implementation of SolanaProvider using RpcClient.
pub struct RealSolanaProvider {
    client: RpcClient,
}

impl RealSolanaProvider {
    pub fn new(rpc_url: String) -> Self {
        Self {
            client: RpcClient::new(rpc_url),
        }
    }
}

#[async_trait]
impl SolanaProvider for RealSolanaProvider {
    fn simulate_transaction(&self, transaction: &Transaction) -> Result<Response<RpcSimulateTransactionResult>, ClientError> {
        self.client.simulate_transaction(transaction)
    }
    fn send_transaction(&self, transaction: &Transaction) -> Result<Signature, ClientError> {
        self.client.send_transaction(transaction)
    }
    fn get_latest_blockhash(&self) -> Result<(Hash, u64), ClientError> {
        self.client.get_latest_blockhash_with_commitment(self.client.commitment())
    }
    fn get_balance(&self, pubkey: &Pubkey) -> Result<u64, ClientError> {
        self.client.get_balance(pubkey)
    }
    fn get_account(&self, pubkey: &Pubkey) -> Result<Account, ClientError> {
        self.client.get_account(pubkey)
    }
    fn get_recent_prioritization_fees(&self, pubkeys: &[Pubkey]) -> Result<Vec<RpcPrioritizationFee>, ClientError> {
        self.client.get_recent_prioritization_fees(pubkeys)
    }
    fn get_token_account_balance(&self, pubkey: &Pubkey) -> Result<serde_json::Value, ClientError> {
        self.client.get_token_account_balance(pubkey).map(|b| serde_json::to_value(b).unwrap())
    }
    fn get_signature_statuses(&self, signatures: &[Signature]) -> Result<Response<Vec<Option<serde_json::Value>>>, ClientError> {
        let resp = self.client.get_signature_statuses(signatures)?;
        let value = resp.value.into_iter().map(|opt| opt.map(|s| serde_json::to_value(s).unwrap())).collect();
        Ok(Response { context: resp.context, value })
    }
    fn get_slot(&self) -> Result<u64, ClientError> {
        self.client.get_slot()
    }
}

pub struct ChainBridgeGrpcService {
    provider: Arc<dyn SolanaProvider>,
    vault: Arc<crate::vault::VaultTransitClient>,
    transit_key_name: String,
}

impl ChainBridgeGrpcService {
    pub fn new(provider: Arc<dyn SolanaProvider>, vault: Arc<crate::vault::VaultTransitClient>) -> Self {
        let transit_key_name = std::env::var("CHAIN_BRIDGE_VAULT_KEY_NAME")
            .unwrap_or_else(|_| "gridtokenx-bridge".to_string());

        Self {
            provider,
            vault,
            transit_key_name,
        }
    }

    pub fn provider(&self) -> Arc<dyn SolanaProvider> {
        self.provider.clone()
    }

    fn extract_role(&self, ctx: &Context) -> ServiceRole {
        // Primary path: SPIFFE URI from verified TLS client certificate
        // We look for it in headers if we can't get it from extensions easily with connectrpc
        if let Some(spiffe_id) = ctx.headers.get("z-gridtokenx-spiffe-id").and_then(|v| v.to_str().ok()) {
            let identity = gridtokenx_blockchain_core::auth::SpiffeIdentity(spiffe_id.to_string());
            let role = ServiceRole::from(&identity);
            info!("mTLS peer verified (via header) → identity: {} role: {}", spiffe_id, role);
            return role;
        }

        // Dev-only fallback: trust everything when insecure mode is explicitly enabled
        if std::env::var("CHAIN_BRIDGE_INSECURE").map(|v| v.to_lowercase() == "true").unwrap_or(false) {
            warn!("⚠️ Granting ADMIN role due to CHAIN_BRIDGE_INSECURE mode");
            return ServiceRole::Admin;
        }

        // Dev-only fallback: trust header only when escape hatch env var is set
        if std::env::var("CHAIN_BRIDGE_ALLOW_HEADER_AUTH").is_ok() {
            warn!("⚠️ Using header-based auth (dev mode only)");
            return ServiceRole::from_headers(&ctx.headers);
        }

        ServiceRole::Unknown
    }

    /// Reusable signing and submission logic for both gRPC and NATS
    pub async fn sign_and_submit(&self, serialized_tx: &[u8], key_id: &str) -> anyhow::Result<(Signature, u64)> {
        let mut transaction: Transaction = bincode::deserialize(serialized_tx)
            .map_err(|e| anyhow::anyhow!("Invalid transaction: {}", e))?;

        if key_id == "platform_admin" {
            let bh = self.provider.get_latest_blockhash()
                .map_err(|e| anyhow::anyhow!("Failed to get blockhash: {}", e))?;
            
            transaction.message.recent_blockhash = bh.0;

            // Vault Transit signing flow
            // 1. Get the message data to sign
            let message_data = transaction.message_data();
            
            // 2. Request signature from Vault
            let signature = self.vault.sign_message(&self.transit_key_name, &message_data).await
                .context("Vault Transit signing failed")?;

            // 3. Attach signature to transaction
            // Solana transactions have a fixed size signatures vector corresponding to num_required_signatures
            if transaction.signatures.is_empty() {
                transaction.signatures.push(signature);
            } else {
                transaction.signatures[0] = signature;
            }

            info!("✅ Transaction signed remotely via Vault Transit for platform_admin");
            
            tracing::debug!(
                correlation_id = %key_id,
                num_accounts = transaction.message.account_keys.len(),
                num_instructions = transaction.message.instructions.len(),
                "Transaction submitted"
            );
        } else if !key_id.is_empty() {
             return Err(anyhow::anyhow!("Key ID not authorized: {}", key_id));
        }

        let sig = self.provider.send_transaction(&transaction)
            .map_err(|e| anyhow::anyhow!("Solana RPC error: {}", e))?;

        Ok((sig, 0))
    }
}

impl ChainBridgeService for ChainBridgeGrpcService {
    async fn simulate_transaction(
        &self,
        ctx: Context,
        request: OwnedView<SimulateTransactionRequestView<'static>>,
    ) -> Result<(SimulateTransactionResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[ServiceRole::TradingMatcher, ServiceRole::OracleBridge, ServiceRole::IamService, ServiceRole::Admin])
            .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received simulate_transaction request for key_id: {}", request.key_id);
        
        let tx: Transaction = bincode::deserialize(&request.serialized_transaction)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, e.to_string()))?;

        match self.provider.simulate_transaction(&tx) {
            Ok(resp) => {
                let mut response = SimulateTransactionResponse::default();
                response.success = resp.value.err.is_none();
                response.compute_units_consumed = resp.value.units_consumed.unwrap_or(0);
                response.logs = resp.value.logs.unwrap_or_default();
                Ok((response, ctx))
            }
            Err(e) => Err(ConnectError::new(ErrorCode::Internal, e.to_string())),
        }
    }

    async fn submit_transaction(
        &self,
        ctx: Context,
        request: OwnedView<SubmitTransactionRequestView<'static>>,
    ) -> Result<(SubmitTransactionResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[ServiceRole::TradingMatcher, ServiceRole::OracleBridge, ServiceRole::IamService, ServiceRole::Admin])
            .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received submit_transaction request with key_id: {}", request.key_id);
        
        let result = self.sign_and_submit(&request.serialized_transaction, &request.key_id).await;

        match result {
            Ok((sig, slot)) => {
                let mut response = SubmitTransactionResponse::default();
                response.success = true;
                response.signature = sig.to_string();
                response.error_message = String::new();
                response.slot = slot;
                Ok((response, ctx))
            }
            Err(e) => {
                let err_msg = format!("{:#}", e);
                let code = if err_msg.contains("authorized") || err_msg.contains("PermissionDenied") {
                    ErrorCode::PermissionDenied
                } else {
                    ErrorCode::Internal
                };
                Err(ConnectError::new(code, err_msg))
            }
        }
    }

    async fn get_balance(
        &self,
        ctx: Context,
        request: OwnedView<GetBalanceRequestView<'static>>,
    ) -> Result<(GetBalanceResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway, 
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_balance for {}", request.pubkey);
        
        let pubkey = Pubkey::from_str(&request.pubkey)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, e.to_string()))?;

        match self.provider.get_balance(&pubkey) {
            Ok(lamports) => {
                let mut response = GetBalanceResponse::default();
                response.lamports = lamports;
                Ok((response, ctx))
            }
            Err(e) => Err(ConnectError::new(ErrorCode::Internal, e.to_string())),
        }
    }

    async fn get_account_data(
        &self,
        ctx: Context,
        request: OwnedView<GetAccountDataRequestView<'static>>,
    ) -> Result<(GetAccountDataResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway, 
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_account_data for {}", request.pubkey);
        
        let pubkey = Pubkey::from_str(&request.pubkey)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, e.to_string()))?;

        match self.provider.get_account(&pubkey) {
            Ok(account) => {
                let mut response = GetAccountDataResponse::default();
                response.exists = true;
                response.data = account.data;
                Ok((response, ctx))
            }
            Err(e) => {
                if e.to_string().contains("AccountNotFound") {
                     let mut response = GetAccountDataResponse::default();
                     response.exists = false;
                     response.data = vec![];
                     Ok((response, ctx))
                } else {
                    Err(ConnectError::new(ErrorCode::Internal, e.to_string()))
                }
            }
        }
    }

    async fn get_latest_blockhash(
        &self,
        ctx: Context,
        _request: OwnedView<GetLatestBlockhashRequestView<'static>>,
    ) -> Result<(GetLatestBlockhashResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_latest_blockhash");
        
        match self.provider.get_latest_blockhash() {
            Ok((blockhash, last_valid_block_height)) => {
                let mut response = GetLatestBlockhashResponse::default();
                response.blockhash = blockhash.to_string();
                response.last_valid_block_height = last_valid_block_height;
                Ok((response, ctx))
            }
            Err(e) => Err(ConnectError::new(ErrorCode::Internal, e.to_string())),
        }
    }

    async fn get_recent_prioritization_fees(
        &self,
        ctx: Context,
        request: OwnedView<GetRecentPrioritizationFeesRequestView<'static>>,
    ) -> Result<(GetRecentPrioritizationFeesResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_recent_prioritization_fees for {} accounts", request.account_keys.len());
        
        let account_keys: Vec<Pubkey> = request.account_keys.iter()
            .map(|k| Pubkey::from_str(k).map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, format!("Invalid account key '{}': {}", k, e))))
            .collect::<Result<Vec<_>, _>>()?;

        match self.provider.get_recent_prioritization_fees(&account_keys) {
            Ok(fees) => {
                let mut response = GetRecentPrioritizationFeesResponse::default();
                response.fees = fees.into_iter().map(|f| {
                    let mut fee = PrioritizationFee::default();
                    fee.slot = f.slot;
                    fee.prioritization_fee = f.prioritization_fee;
                    fee
                }).collect();
                Ok((response, ctx))
            }
            Err(e) => Err(ConnectError::new(ErrorCode::Internal, e.to_string())),
        }
    }

    async fn get_token_account_balance(
        &self,
        ctx: Context,
        request: OwnedView<GetTokenAccountBalanceRequestView<'static>>,
    ) -> Result<(GetTokenAccountBalanceResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway, 
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_token_account_balance for {}", request.pubkey);
        
        let pubkey = Pubkey::from_str(&request.pubkey)
            .map_err(|e| ConnectError::new(ErrorCode::InvalidArgument, e.to_string()))?;

        match self.provider.get_token_account_balance(&pubkey) {
            Ok(balance) => {
                let mut response = GetTokenAccountBalanceResponse::default();
                response.amount = balance["amount"].as_str().unwrap_or("0").to_string();
                response.decimals = balance["decimals"].as_u64().unwrap_or(0) as u32;
                response.ui_amount = balance["ui_amount"].as_f64().unwrap_or(0.0);
                Ok((response, ctx))
            }
            Err(e) => Err(ConnectError::new(ErrorCode::Internal, e.to_string())),
        }
    }

    async fn get_signature_status(
        &self,
        ctx: Context,
        request: OwnedView<GetSignatureStatusRequestView<'static>>,
    ) -> Result<(GetSignatureStatusResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::ApiGateway, 
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_signature_status for {}", request.signature);
        
        let signature = Signature::from_str(&request.signature)
            .map_err(|e: solana_sdk::signature::ParseSignatureError| ConnectError::new(ErrorCode::InvalidArgument, e.to_string()))?;

        match self.provider.get_signature_statuses(&[signature]) {
            Ok(resp) => {
                if let Some(Some(status)) = resp.value.first() {
                    let mut response = GetSignatureStatusResponse::default();
                    response.confirmed = status["confirmations"].as_u64().is_some() || status["err"].is_null();
                    response.status = status["confirmation_status"].as_str().unwrap_or("Unknown").to_string();
                    response.error = if status["err"].is_null() { "".to_string() } else { status["err"].to_string() };
                    Ok((response, ctx))
                } else {
                    let mut response = GetSignatureStatusResponse::default();
                    response.confirmed = false;
                    response.status = "NotFound".to_string();
                    Ok((response, ctx))
                }
            }
            Err(e) => Err(ConnectError::new(ErrorCode::Internal, e.to_string())),
        }
    }

    async fn get_slot(
        &self,
        ctx: Context,
        _request: OwnedView<GetSlotRequestView<'static>>,
    ) -> Result<(GetSlotResponse, Context), ConnectError> {
        let role = self.extract_role(&ctx);
        role.require_any(&[
            ServiceRole::TradingApi, 
            ServiceRole::TradingMatcher, 
            ServiceRole::OracleBridge, 
            ServiceRole::IamService, 
            ServiceRole::Admin
        ])
        .map_err(|(_, msg)| ConnectError::permission_denied(msg))?;

        info!("🔗 gRPC Received get_slot");
        
        match self.provider.get_slot() {
            Ok(slot) => {
                let mut response = GetSlotResponse::default();
                response.slot = slot;
                Ok((response, ctx))
            }
            Err(e) => Err(ConnectError::new(ErrorCode::Internal, e.to_string())),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use solana_sdk::signature::{Keypair, Signer};
    use solana_client::rpc_response::{Response, RpcResponseContext, RpcSimulateTransactionResult};
    use solana_sdk::system_instruction;
    use buffa::view::OwnedView;
    use connectrpc::{Context, ErrorCode};

    struct MockSolanaProvider {
    }

    #[async_trait]
    impl SolanaProvider for MockSolanaProvider {
        fn simulate_transaction(&self, _transaction: &Transaction) -> Result<Response<RpcSimulateTransactionResult>, ClientError> {
            Ok(Response {
                context: RpcResponseContext { slot: 100, api_version: None },
                value: RpcSimulateTransactionResult {
                    err: None,
                    logs: Some(vec!["Program log: Hello".to_string()]),
                    accounts: None,
                    units_consumed: Some(100),
                    return_data: None,
                    inner_instructions: None,
                    loaded_accounts_data_size: None,
                    replacement_blockhash: None,
                },
            })
        }
        fn send_transaction(&self, _transaction: &Transaction) -> Result<Signature, ClientError> {
            Ok(Signature::from([0u8; 64]))
        }
        fn get_latest_blockhash(&self) -> Result<(Hash, u64), ClientError> {
            Ok((Hash::default(), 1000))
        }
        fn get_balance(&self, _pubkey: &Pubkey) -> Result<u64, ClientError> {
            Ok(1000000000) // 1 SOL
        }
        fn get_account(&self, _pubkey: &Pubkey) -> Result<Account, ClientError> {
            Ok(Account {
                lamports: 1000000000,
                data: vec![1, 2, 3],
                owner: Pubkey::default(),
                executable: false,
                rent_epoch: 0,
            })
        }
        fn get_recent_prioritization_fees(&self, _pubkeys: &[Pubkey]) -> Result<Vec<RpcPrioritizationFee>, ClientError> {
            Ok(vec![RpcPrioritizationFee {
                slot: 100,
                prioritization_fee: 1000,
            }])
        }
        fn get_token_account_balance(&self, _pubkey: &Pubkey) -> Result<serde_json::Value, ClientError> {
            Ok(serde_json::json!({
                "ui_amount": 10.5,
                "decimals": 9,
                "amount": "10500000000",
                "ui_amount_string": "10.5"
            }))
        }
        fn get_signature_statuses(&self, _signatures: &[Signature]) -> Result<Response<Vec<Option<serde_json::Value>>>, ClientError> {
            Ok(Response {
                context: RpcResponseContext { slot: 101, api_version: None },
                value: vec![Some(serde_json::json!({
                    "slot": 100,
                    "confirmations": 31,
                    "err": null,
                    "confirmation_status": "Confirmed"
                }))],
            })
        }
        fn get_slot(&self) -> Result<u64, ClientError> {
            Ok(100)
        }
    }

    fn create_test_service() -> ChainBridgeGrpcService {
        ChainBridgeGrpcService {
            provider: Arc::new(MockSolanaProvider {}),
            vault: Arc::new(crate::vault::VaultTransitClient::new("http://localhost:8200".to_string(), "root".to_string())),
            transit_key_name: "test-key".to_string(),
        }
    }

    fn authenticated_ctx() -> Context {
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/admin".parse().unwrap());
        ctx
    }

    #[tokio::test]
    async fn test_get_balance() {
        let service = create_test_service();
        let pubkey = Pubkey::new_unique();
        let mut request_owned = GetBalanceRequest::default();
        request_owned.pubkey = pubkey.to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_balance(authenticated_ctx(), request).await.unwrap();
        assert_eq!(resp.lamports, 1000000000);
    }

    #[tokio::test]
    async fn test_simulate_transaction() {
        let service = create_test_service();
        let from = Keypair::new();
        let to = Pubkey::new_unique();
        let ix = solana_sdk::system_instruction::transfer(&from.pubkey(), &to, 1000);
        let tx = Transaction::new_with_payer(&[ix], Some(&from.pubkey()));
        let serialized_tx = bincode::serialize(&tx).unwrap();

        let mut request_owned = SimulateTransactionRequest::default();
        request_owned.serialized_transaction = serialized_tx;
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.simulate_transaction(authenticated_ctx(), request).await.unwrap();
        assert!(resp.success);
        assert_eq!(resp.compute_units_consumed, 100);
        assert_eq!(resp.logs[0], "Program log: Hello");
    }

    #[tokio::test]
    async fn test_submit_transaction_with_platform_admin() {
        let service = create_test_service();
        let to = Pubkey::new_unique();
        let ix = solana_sdk::system_instruction::transfer(&Pubkey::default(), &to, 1000);
        let tx = Transaction::new_with_payer(&[ix], Some(&Pubkey::default()));
        let serialized_tx = bincode::serialize(&tx).unwrap();

        let mut request_owned = SubmitTransactionRequest::default();
        request_owned.serialized_transaction = serialized_tx;
        request_owned.key_id = "platform_admin".to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.submit_transaction(authenticated_ctx(), request).await.unwrap();
        assert!(resp.success);
        assert!(!resp.signature.is_empty());
    }

    fn unauthenticated_ctx() -> Context {
        let mut ctx = Context::default();
        ctx.headers.insert("z-gridtokenx-spiffe-id", "spiffe://gridtokenx.th/prod/guest".parse().unwrap());
        ctx
    }

    #[tokio::test]
    async fn test_submit_transaction_unauthorized() {
        let service = create_test_service();
        let mut request_owned = SubmitTransactionRequest::default();
        request_owned.key_id = "unknown_user".to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let result = service.submit_transaction(unauthenticated_ctx(), request).await;
        assert!(result.is_err());
        assert_eq!(result.err().unwrap().code, ErrorCode::PermissionDenied);
    }

    #[tokio::test]
    async fn test_get_account_data_exists() {
        let service = create_test_service();
        let mut request_owned = GetAccountDataRequest::default();
        request_owned.pubkey = Pubkey::new_unique().to_string();
        let request = OwnedView::from_owned(&request_owned).unwrap();

        let (resp, _) = service.get_account_data(authenticated_ctx(), request).await.unwrap();
        assert!(resp.exists);
        assert_eq!(resp.data, vec![1, 2, 3]);
    }
}
